### ISSUE TITLE
Create an instance of postgreSQL on docker-compose

### ISSUE THREAD

**Issue by icaropablo2** [fdavidgithub/sensoriando_webservice#54]
When we run the project for the first time, the API is expected to have an instance of PostgreSQL running locally, let's containerize the database to eliminate the need to install and manage a local instance of the database.

![image](https://github.com/fdavidgithub/sensoriando_webservice/assets/8972126/b79e2919-f165-4cb8-a2d9-5c39c0a4d77d)

**Comment by fdavidgithub** [comment]
First, you need install https://github.com/fdavidgithub/sensoriando_core 
To create the database container and others requirements for this repository.

**Comment by fdavidgithub** [comment]
https://github.com/fdavidgithub/sensoriando_webservice/commit/14fe56c65d47ecf8efe94b89a65cad3dbe8c494a
